language: java
jdk:
  - openjdk11

before_install: openssl aes-256-cbc -K $encrypted_a48e15357eff_key -iv $encrypted_a48e15357eff_iv -in foreman-production-dff7d0598319.json.enc -out foreman-production-dff7d0598319.json -d

install: mvn install --settings .travis.settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q

script: mvn verify --settings .travis.settings.xml -q

deploy:
  - provider: script
    script: mvn deploy --settings .travis.settings.xml -DskipTests=true -q
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy --settings .travis.settings.xml -DskipTests=true -q
    skip_cleanup: true
    on:
      branch: develop
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "target/*.tar.bz2"
      - "target/*.tar.gz"
      - "target/*.zip"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
    name: $TRAVIS_BRANCH
