apps.manifest: https://api.foreman.mn/api/v2/manifests

upgrade:
  check:
    frequency: 900000

spring.main.web-application-type: none

client:
  id: test-client-id
  apiKey: test-api-key
agent:
  home: target
  dist: ${agent.home}\dist
  scale: 1