apps.manifest: https://api.foreman.mn/api/v2/manifests

upgrade:
  check:
    frequency: 300000

spring.main.web-application-type: none

client:
  id: test-client-id
  apiKey: test-api-key
agent:
  home: target
  dist: ${agent.home}\dist\private
  colo:
    dist: ${agent.home}\dist\colo
    enabled: false
  scale: 1