name: workflow

on:
  push:
    branches:
      - '*'

jobs:
  call-workflow-passing-data:
    uses: foremanmining/workflows/.github/workflows/java.yml
    with:
      result-folder: './'
      gcs-bucket: windows-agent-releases