name: workflow

on:
  push:
    branches:
      - '*'

jobs:
  call-workflow:
    uses: foremanmining/workflows/.github/workflows/java.yml@main
    with:
      result-folder: './'
      gcs-bucket: windows-agent-releases